import type { Translation } from './de';
export const en: Translation = {
  nav: ['About', 'Experience', 'Projects', 'Education', 'Skills', 'Community', 'Contact'],
  skip:'Skip to content', menu:'Open menu', close:'Close menu', light:'Switch to light theme', dark:'Switch to dark theme',
  eyebrow:'COMPUTER SCIENCE × MATHEMATICS', hello:"Hi, I'm", hero:'Johannes Gölz.',
  headline:'Curious about why.\nReady to figure out how.', intro:'Computer science & mathematics student at KIT. Combining analytical thinking with the joy of building things.',
  contact:'Get in touch', projects:'Explore projects', scroll:'Discover more', location:'Karlsruhe, Germany', portrait:'Portrait coming soon', portraitNote:'Computer science ∩ Mathematics',
  aboutTitle:'Where theory meets\npossibility.', about:["I'm interested in turning mathematical foundations into practical software. My studies at KIT bring together computer science and mathematics; I'm currently pursuing a master's in computer science.","IT consulting, data science and tutoring have given me different perspectives. I enjoy understanding connections, trying out ideas and making knowledge easier to share."],
  focus:'WHAT DRIVES ME', focusTitle:'Understand. Build. Share.', focusText:'Machine learning, backend development and the mathematics behind them.',
  experienceTitle:'Learning by\ndoing.', experienceNote:'Perspectives from practice and teaching.',
  jobs:[{org:'Objektkultur',role:'Working student · IT consulting',duration:'1 year',text:'Practical experience in IT consulting alongside my studies.',tags:['IT consulting','Software']},{org:'ICIS',role:'Internship · Data science',duration:'1 semester',text:'A semester focused on data science and working with data.',tags:['Data science','Analysis']},{org:'Karlsruhe Institute of Technology',role:'Tutor · Computer science & mathematics',duration:'4 courses',text:'Linear Algebra 1 & 2, Digital Systems and Computer Architecture – one semester each.',tags:['Teaching','Mathematics','Computer science']}],
  projectsTitle:'From an idea\nto an application.', projectLabel:'SELECTED PROJECTS', appTitle:'An idea. An app.', appText:'An app built with Flutter and published on the Google Play Store.', appLink:'View on Google Play', backendTitle:'Software for research.', backendText:'Contributed to a Fraunhofer web app project with a Java backend.', backendLink:'View project', todoLink:'TODO · Add project link', illustrative:'Abstract project illustration',
  educationTitle:'Two disciplines.\nOne curious mind.', education:[{degree:"Master's studies",subject:'Computer science',note:'Current focus'},{degree:"Bachelor's studies",subject:'Mathematics',note:'Mathematical foundations'},{degree:"Bachelor's studies",subject:'Computer science',note:'Algorithms & systems'}],
  skillsTitle:'My toolkit.', skillGroups:['Programming & ML','Cloud & backend','Tools','Languages'], skills:[['Java','Dart / Flutter','Machine learning','Data science'],['Java backend','Web applications'],['TODO · Add specific tools'],['TODO · Add languages & proficiency']],
  engagementTitle:'Better, together.', engagement:[{title:'Linkit · Datascience Group',text:'Sharing ideas about data science and taking part in the Global AI Hackathon at MIT.',tag:'Data science & community'},{title:'Computer science student council',text:'Involvement in the computer science student council and student representation.',tag:'Student representation'}],
  contactTitle:'A good idea starts\nwith a conversation.',contactText:"Technology, a shared project or a fresh perspective – I'd love to connect.",emailTodo:'TODO · Add email address',repoTodo:'TODO · Link GitHub repository',footer:'Built with curiosity.',
};
